name: Build and tests run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Instal dependencies 
      run: npm install
    - name: Install playwright 
      run: npx playwright install
    - name: Start the server 
      run: npm run server &
    - name: Start the frond end 
      run: npm start &
    - name: Run the indegration test  
      run: npm run test
